version: '3'

services:
  web:
    build: ./src
    ports:
      - "80:80"
    depends_on:
      - postgres
    links:
      - postgres
    restart: always

  postgres:
    image: postgres:9.3-alpine 
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_DB: swaggerdb

